  services:
    # Backend 
    backend:
      image: dohoangphong/fongnosudo-be
      container_name: fongnosudo-backend
      environment:
        - DATABASE_URL=${DATABASE_URL}
        - JWT_SECRET_KEY=${JWT_SECRET_KEY}
        - FLASK_ENV=${FLASK_ENV:-development}
        - USER_ADMIN=${USER_ADMIN}
        - USER_ADMIN_PASSWORD=${USER_ADMIN_PASSWORD}
      volumes:
        - ../fongnosudo-be/uploads:/app/uploads
      ports:
        - "${BACKEND_PORT:-5000}:${BACKEND_PORT:-5000}"
      networks:
        - fongnosudo-network
      restart: unless-stopped
      healthcheck:
        test: ["CMD", "curl", "-f", "http://127.0.0.1:${BACKEND_PORT:-5000}/"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 40s

    # Frontend 
    frontend:
      image: dohoangphong/fongnosudo-fe
      container_name: fongnosudo-frontend
      ports:
        - "${FRONTEND_PORT:-3000}:80"
      depends_on:
        - backend
      networks:
        - fongnosudo-network
      restart: unless-stopped
      healthcheck:
        test: ["CMD", "curl", "-f", "http://127.0.0.1/"]
        interval: 30s
        timeout: 10s
        retries: 3

  networks:
    fongnosudo-network:
      driver: bridge